// Generated by CoffeeScript 1.9.1
(function() {
  var fs, localroot, path, reqerr, worker, worker_path;

  fs = require('fs');

  path = require('path');

  localroot = path.resolve('.');

  if (fs.existsSync('f5file.js')) {
    worker_path = path.join(localroot, 'f5file.js');
    console.log(worker_path);
    debugger;
    try {
      worker = require(worker_path);
    } catch (_error) {
      reqerr = _error;
      console.log(reqerr.message);
      return;
    }
  } else {
    worker = {
      "do": function() {}
    };
  }

  exports["do"] = worker["do"];

}).call(this);
